services:
  minetest:
    container_name: minetest-server
    image: sayk/minetest-server:latest
    restart: unless-stopped
    ports:
      - 30000:30000/udp
    volumes:
      - ./minetest-data/minetest-map:/minetest/worlds/minetest-map
      - ./minetest-data/mods:/minetest/mods/
      - ./minetest-data/texturespack:/minetest/textures/base/pack
    command: ./bin/minetestserver --world /minetest/bin/../worlds/minetest-map --gameid minetest_game